apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mywebapp.fullname" . }}
  labels:
    {{- include "mywebapp.labels" . | nindent 4 }}
data:
  index.html: |
    {{ .Values.config.homepage | nindent 4 }}
